### ISSUE TITLE
Create a standard data model/template

### ISSUE THREAD

**Issue by elaguerta** [sfbrigade/data-covid19-sfbayarea#30] opened 2020-04-14 20:04 UTC
![image](https://user-images.githubusercontent.com/12928553/79268956-7a25c300-7e50-11ea-89bf-30ab9fe6590a.png)

**Comment by elaguerta** [comment] 2020-04-14 20:08
Write a template .json or .csv with desired columns. The model needs to account for discrepancies in totals, for examples, some counties report Total Tests including pending tests, other counties exclude pending tests.

**Comment by kwonangela7** [comment] 2020-04-16 04:21
Thanks for all your work Elaine! :) I also messaged you on Slack, but I went ahead and assigned myself to this.

**Comment by elaguerta** [comment] 2020-04-16 19:12
Hi Angela! Thanks so much for jumping on board. 
Yes, let's start by doing a template. I think we should actually start with a template .csv file since that will be easier to share with the rest of the project. The idea is to get some standard column format, that we can then use to target scrapers for each county.
For each column, I think we should have metadata describing the datapoint. For example, if we decide that Total Tests excludes pending tests, we need to note that. This will require some further research into how each county reports each specific datapoint. Other metadata might include: 

- type (string, number)
- update_time (timestamp)
- composite_var (some way to indicate if this number is not directly reported. For example, some of the datapoints will have to be obtained by summing over over subtracting the numbers that are directly reported. In that case composite_var would store the calculation we made to arrive at this datapoint.)

**Comment by kwonangela7** [comment] 2020-04-17 04:13
Gotcha - I'll go ahead and start this. Just to make sure I'm on the same page, when you say "start with a template .csv file" is this something I need to do with code, or is it sufficient to create it in Excel or an editor and save it as a csv?

**Comment by elaguerta** [comment] 2020-04-17 05:06
Creating a .csv in Excel/editor is sufficient. When you have a draft for
feedback, could you place the file as an added file in a pull request, so
that the team can review and comment on it?

**Comment by kwonangela7** [comment] 2020-04-23 00:38
Hello! I may have over thought this task/my definition of metadata might be too limited, but here's my draft for the common data model template. I think it looks a bit underwhelming (and the metadata values are maybe too obvious, or for some column headers there aren't many metadata values, so maybe I did something incorrectly?) 

Some of the metadata values (like the ones for Tests) perhaps shouldn't be metadata values, or should be separated into a group for another data column header. I also wasn't sure if I was to have a "Type" column, but I added that in there since it seemed to be an important part of the template.

 I put a few other comments in the excel file as well. I thought a Google link would be an easier way to collaborate/have people make comments on, so [here it is](https://docs.google.com/spreadsheets/d/1BJAXbMrsSueVUwaSLO26zA8e7RauLE53xy_Sjk412Ec/edit?usp=sharing). The template draft is in the first tab named "CDM" (the other tabs were for my own process of creating the template).

 Am looking forward to improving this with everyone's feedback!

**Comment by kwonangela7** [comment] 2020-04-23 03:11
Logan and Vivek gave me feedback and we talked through an example of something Logan was looking for. Here's a mockup of what I'm shooting for now. I'll go ahead and create a JSON template for 1-2 of the counties, get some feedback to make sure I'm still on the same page as everyone, and then finish up the rest by next week. @elaguerta does the mockup look good to you as well/is this what you had in mind?

![image](https://user-images.githubusercontent.com/13878545/80054722-efd70200-84d4-11ea-92a3-a148cd1c1ddd.png)

**Comment by Mr0grog** [comment] 2020-04-23 06:07
Jumping in here to link this up with sfbrigade/stop-covid19-sfbayarea#36: the charts on the site currently show a “last updated” date, but it’s actually just the latest date in the dataset, not the date/time as of which the data was gathered or was accurate.

We’d like to show a more “true” update time there, and we’d like it to be an actual time, not just a date. It would be helpful if the model included that information, whether county-by-county or just for the whole dataset.

**Comment by kengoy** [comment] 2020-04-23 06:18
Hey @kwonangela7 @ldtcooper @elaguerta, thanks so much for this work! I wanted to catch up with you in today's meeting what data format is going to look like. Now it makes sense to me. We want to make sure we are covering all the necessary data to satisfy Nico's UI wireframe https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/COVID-19-Tracker-by-Code-for-SF?node-id=1175%3A103.

Here are the list I think
- Time series of Confirmed cases per county
- Time series of Death cases per county
- Time series of Tested per county 
- Latest number of Confirmed cases by Race per county
- Latest number of Confirmed cases by Age per county
- Latest number of Confirmed cases by Genger per county
- Last Updated data and time for each data set.
- Population per county

Followings are nice to have but frontend side can also sum up or calculate using the above dataset.
- Latest Total number of Confirmd Cases in the Bay Area
- Daily increase number and percentage in the Bay Area
- Growth rate vs last week (7 days ago I guess) in the Bay Area
- Latest Total number of Death Cases in the Bay Area
- Confirmed Cases/1000 people  
- Total Test conducted per county
- Test Positive rate per county
- Confirmd cases: Percentatge of Bay Area Total per county
- Deaths cases: Percentatge of Bay Area Total per county

Not sure if we can include the following data in our format.
- Confirmed Cases/1000 people in California
- Confirmed Cases/1000 people in United States

**Comment by elaguerta** [comment] 2020-04-23 16:17
@kwonangela7 Thanks so much, both the excel file and mock-up .json were helpful for me. I think the .json format works better because you can express nested structures. I was visualizing a prototype that is the union of all the possible data points available for the counties. Then we can keep every county the same shape and explicitly state that data points are not available. The prototype would be posted as part of a contribution guide on github for the data fetching efforts, as well as part of the documentation for the eventual API. I do not think we need a mock-up for each of the counties, though you might have to start by mocking up individual counties and then taking the union of them. If you choose SF and Santa Clara, that would give you full coverage of the data points available (a green column on the [Data Coverage Spreadsheet](https://docs.google.com/spreadsheets/d/1fhdF587nhBlychWvmMwPs2PwGy9ffqiH06ZZhEitVfo/edit?usp=sharing)). I think we want to have a general prototype, let the data scrapers catch up, and then re-evaluate. Unless, @ldtcooper do you think we should do a mockup of each county?

In addition to the green columns on the data coverage spreadsheet, we should include:
- Population
- Link to data source
- Last updated date and time (per county) @Mr0grog 
- Cases, Deaths, and Tests should each include a time-series @kengo-sony 

With that, we'll be able to express Nico's wireframe (though not for all 9 counties. We'll cross that bridge eventually!)

@vishakh-arora welcome! please add any thoughts/comments.
@collincr keeping you in the loop.

**Comment by ldtcooper** [comment] 2020-04-23 17:43
I don't see much of a reason to make a mockup of each county. The idea is to put data coming from multiple sources into the same format for ease of cleaning, formatting, and API use; we want to keep the outgoing JSON looking pretty much the same no matter the county. 
The only differences should be which data series (e.g. `[County].data[key]`) or demographics (`[County].data[key].tabulations[demographic`) the different counties have. Depending on what's easier for the frontend, we could either leave series with no data out of the JSON (e.g. not have a `deaths` key if a county doesn't publish deaths) or send all possible data points, but give them values of `null`, depending on what's easier for the frontend team.
I like @elaguerta 's idea of doing SF and Santa Clara as prototypes to get a good idea of all the possible data points

**Comment by kwonangela7** [comment] 2020-04-24 03:29
@Mr0grog Noted, thank you!

@kengoy thanks for your comment, and for making this list! I've been in communication with Niko about visualization related things, so I think I'm on the same page. I'll follow up with any questions here if I have any.

@elaguerta "I was visualizing a prototype that is the union of all the possible data points available for the counties." - I also was visualizing this. 

"I think we want to have a general prototype, let the data scrapers catch up, and then re-evaluate." - I think that sounds like a good plan.

I'll make sure to include the other datapoints you included as well. Thanks for your comment!

@ldtcooper Sounds good - I'll proceed with @elaguerta's proposed plan and I'll go ahead and work on SF tonight. Will make a pull request when it's ready for feedback.

**Comment by kwonangela7** [comment] 2020-04-24 03:31
also, @frhino asked me to try getting some other people on this ticket so that we can try to get this done faster - I think Josh's goal was Saturday night! :0 

@elaguerta @Mr0grog @kengoy @ldtcooper @vishakh-arora @collincr would you be interested/available to work on this in the next few days? (Saturday being the large workday).

**Comment by kwonangela7** [comment] 2020-05-01 05:28
hi @elaguerta! Logan approved of data_model.json, and I just merged our PR. Just wanted to ask if we are able to close this issue?

**Closed** 2020-05-02 05:05 UTC
